name: dvc_train_pipeline
on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Training run"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          pip install -r requirements.txt
          dvc repro

          git fetch --prune

          echo "## Model Metrics : Comparing with master branch"
          dvc metrics diff --show-md master > report.md
          
          echo "## Results plot" >> report.md

          cml-publish by_region.png --md >> report.md
          cml-send-comment report.md
    

        
          




  

